site_name: EPITA - Documentation
theme: readthedocs
repo_url: https://github.com/cri-epita/epita-doc/
pages:
  - Accueil: 'index.md'
  - Documentation:
    - Mots de passe: 'passwords.md'
    - 'news.md'
  - Procédures:
    - Changement de mot de passe: 'change_password.md'
    - 'redump.md'
