site_name: Epita - Documentation
pages:
  - Accueil: 'index.md'
  - Documentation:
    - Mots de passe: 'passwords.md'
    - News: 'news.md'
  - Procédures:
    - Changement de mot de passe: 'change_password.md'
    - Redump: 'redump.md'
